const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout
	];
};
self.C3_JsPropNameTable = [
	{a679f4cc8d500f3a9d39eef14c: 0},
	{a9020e7413afbcc016b83469184b7f: 0},
	{c7530fa6bef6a89a4351f: 0},
	{d3407b6fbc8733801c47bc13df5a76c: 0},
	{e48f46b1bb97f57302612e19cd2bdc: 0},
	{fd2934dede7336b9a9b21ad83bf: 0},
	{name: 0},
	{health: 0},
	{UIDheart: 0},
	{isdead: 0},
	{speed: 0},
	{边界约束: 0},
	{enermy: 0},
	{子弹: 0},
	{出界销毁: 0},
	{enemybullet: 0},
	{固定: 0},
	{enermyheart: 0},
	{boss: 0},
	{enemy3: 0},
	{enemy2: 0},
	{enemyheart2: 0},
	{enemyheart3: 0},
	{enemyheart4: 0},
	{卢浮宫开始页面: 0},
	{退出按钮: 0},
	{开始按钮: 0},
	{标题_画板: 0},
	{制作人员按钮: 0},
	{继续按钮: 0},
	{暂停: 0},
	{精灵: 0},
	{退出按钮2: 0},
	{重新开始按钮: 0},
	{IMG_: 0},
	{SCORE: 0},
	{scoretext: 0},
	{制作人员图片_画板: 0},
	{标题: 0},
	{lzy_画板: 0},
	{zjy_画板: 0},
	{zkx_画板: 0},
	{zxy_画板: 0},
	{退出按钮3: 0},
	{失败页面_画板: 0},
	{bg: 0},
	{退出按钮4: 0},
	{RESTART: 0},
	{loseanimation: 0},
	{RESTART2: 0},
	{精灵3: 0},
	{退出按钮5: 0},
	{前: 0},
	{正弦运动: 0},
	{IMG_10: 0},
	{IMG_11: 0},
	{IMG_12: 0},
	{IMG_2: 0},
	{IMG_3: 0},
	{IMG_4: 0},
	{IMG_5: 0},
	{IMG_6: 0},
	{IMG_7: 0},
	{IMG_8: 0},
	{IMG_9: 0},
	{人1: 0},
	{皇冠: 0},
	{皇冠2: 0},
	{项链: 0},
	{项链2: 0},
	{键盘: 0},
	{鼠标: 0},
	{音频: 0},
	{canmove: 0},
	{镜头跟随: 0},
	{camera: 0},
	{location: 0},
	{cameralocation: 0},
	{ishit: 0},
	{计时器: 0},
	{mainship: 0},
	{mainshipheart: 0},
	{浏览器: 0},
	{文本: 0},
	{a17d18d00dfebaf23e881c: 0},
	{d857b7ef6d9672af3344deec441ce: 0},
	{Touch: 0},
	{标题2: 0},
	{LOADING: 0},
	{enermycollosion: 0},
	{cameraspeed: 0},
	{score: 0},
	{enemyCount: 0},
	{ToKillUID: 0}
];

self.InstanceType = {
	a679f4cc8d500f3a9d39eef14c: class extends self.ISpriteInstance {},
	a9020e7413afbcc016b83469184b7f: class extends self.ISpriteInstance {},
	c7530fa6bef6a89a4351f: class extends self.ISpriteInstance {},
	d3407b6fbc8733801c47bc13df5a76c: class extends self.ISpriteInstance {},
	e48f46b1bb97f57302612e19cd2bdc: class extends self.ISpriteInstance {},
	fd2934dede7336b9a9b21ad83bf: class extends self.ISpriteInstance {},
	enermy: class extends self.ISpriteInstance {},
	enemybullet: class extends self.ISpriteInstance {},
	enermyheart: class extends self.ISpriteInstance {},
	boss: class extends self.ISpriteInstance {},
	enemy3: class extends self.ISpriteInstance {},
	enemy2: class extends self.ISpriteInstance {},
	enemyheart2: class extends self.ISpriteInstance {},
	enemyheart3: class extends self.ISpriteInstance {},
	enemyheart4: class extends self.ISpriteInstance {},
	卢浮宫开始页面: class extends self.ISpriteInstance {},
	退出按钮: class extends self.ISpriteInstance {},
	开始按钮: class extends self.ISpriteInstance {},
	标题_画板: class extends self.ISpriteInstance {},
	制作人员按钮: class extends self.ISpriteInstance {},
	继续按钮: class extends self.ISpriteInstance {},
	暂停: class extends self.ISpriteInstance {},
	精灵: class extends self.ISpriteInstance {},
	退出按钮2: class extends self.ISpriteInstance {},
	重新开始按钮: class extends self.ISpriteInstance {},
	IMG_: class extends self.ISpriteInstance {},
	SCORE: class extends self.ITextInstance {},
	scoretext: class extends self.ITextInstance {},
	制作人员图片_画板: class extends self.ISpriteInstance {},
	标题: class extends self.ISpriteInstance {},
	lzy_画板: class extends self.ISpriteInstance {},
	zjy_画板: class extends self.ISpriteInstance {},
	zkx_画板: class extends self.ISpriteInstance {},
	zxy_画板: class extends self.ISpriteInstance {},
	退出按钮3: class extends self.ISpriteInstance {},
	失败页面_画板: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	退出按钮4: class extends self.ISpriteInstance {},
	RESTART: class extends self.ISpriteInstance {},
	loseanimation: class extends self.ISpriteInstance {},
	RESTART2: class extends self.ISpriteInstance {},
	精灵3: class extends self.ISpriteInstance {},
	退出按钮5: class extends self.ISpriteInstance {},
	前: class extends self.ISpriteInstance {},
	IMG_10: class extends self.ISpriteInstance {},
	IMG_11: class extends self.ISpriteInstance {},
	IMG_12: class extends self.ISpriteInstance {},
	IMG_2: class extends self.ISpriteInstance {},
	IMG_3: class extends self.ISpriteInstance {},
	IMG_4: class extends self.ISpriteInstance {},
	IMG_5: class extends self.ISpriteInstance {},
	IMG_6: class extends self.ISpriteInstance {},
	IMG_7: class extends self.ISpriteInstance {},
	IMG_8: class extends self.ISpriteInstance {},
	IMG_9: class extends self.ISpriteInstance {},
	人1: class extends self.ISpriteInstance {},
	皇冠: class extends self.ISpriteInstance {},
	皇冠2: class extends self.ISpriteInstance {},
	项链: class extends self.ISpriteInstance {},
	项链2: class extends self.ISpriteInstance {},
	键盘: class extends self.IInstance {},
	子弹: class extends self.ISpriteInstance {},
	鼠标: class extends self.IInstance {},
	音频: class extends self.IInstance {},
	camera: class extends self.ISpriteInstance {},
	cameralocation: class extends self.ISpriteInstance {},
	mainship: class extends self.ISpriteInstance {},
	mainshipheart: class extends self.ISpriteInstance {},
	浏览器: class extends self.IInstance {},
	文本: class extends self.ITextInstance {},
	a17d18d00dfebaf23e881c: class extends self.ISpriteInstance {},
	d857b7ef6d9672af3344deec441ce: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	标题2: class extends self.ISpriteInstance {},
	LOADING: class extends self.ISpriteInstance {},
	enermycollosion: class extends self.ISpriteInstance {}
}